import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "./_components/ThemeProvider";
import Body from "./_components/Body";
import Navbar from "./_components/Navbar";
import RetractableProvider from "./_components/RetractableProvider";
import { auth } from "@/auth";

const publicSans = localFont({
  src: "./fonts/PublicSans-Regular.ttf",
  weight: "400",
});
const publicSansBold = localFont({
  src: "./fonts/PublicSans-Bold.ttf",
  variable: "--font-public-sans-bold",
  weight: "700",
});

export const metadata: Metadata = {
  title: "Personal Finance App",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <ThemeProvider>
        <RetractableProvider>
          <Body
            className={`${publicSans.className} ${publicSansBold.variable} antialiased`}
          >
            <Navbar session={session} />

            <main className="w-full h-full overflow-y-scroll bg-background xl:order-2 px-4 md:px-10 py-6 md:py-8 z-[1] relative">
              {children}
            </main>
          </Body>
        </RetractableProvider>
      </ThemeProvider>
    </html>
  );
}
